package com.example.idioten;

public enum cardEnum {
    //HACE, HONE, HTWO, HTHRRE, HFOUR, HFIVE, HSIX, HSEVEN, HEIGHT, HNINE, HTEN, HJACK, HQUEEN, HKING,
   // DACE, DONE, DTWO, DTHREE, DFOUR, DFIVE, DSIX, DSEVEN, DEIGHT, DNINE, DTEN, DJACK, DQUEEN, DKING
    ACE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,TEN,JACK,QUEEN,KING
}
